
# Font Family SauceCodePro Nerd Font Mono
[font]
normal = { family = "RobotoMono Nerd Font Mono", style = "Regular" }
bold = { family = "RobotoMono Nerd Font Mono", style = "Bold" }
italic = { family = "RobotoMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font Mono", style = "SemiBold Italic" }
